name: Notify

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - ".assets/**"
      - "**.md"
      - "LICENSE-**"

jobs:
  notify-change:
    runs-on: ubuntu-latest
    steps:
      - name: notify to the package.erg-lang.org repository
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mtshiba/package.erg-lang.org/dispatches \
            -d '{"event_type":"notification-push-main","client_payload":{"msg": "a change has been pushed to main"}}'
